return {
    "Annihilator Stealth",
    "B-11 Strikeforce",
    "Akula",
    "Pyro",
    "Scramjet",
    "FH-1 Hunter",
    "Vigilante",
    "APC",
    "Chernobog",
    "Deluxo",
    "Ruiner 2000",
    "P-996 LAZER",
    "LF-22 Starling",
    "Hydra",
    "Thruster",
    "Stromberg",
    "P-45 Nokota",
    "Oppressor",
    "Oppressor Mk II",
    "Toreador",
    "Savage",
    "Sea Sparrow",
    "Sparrow",
    "V-65 Molotok",
    "Buzzard Attack Chopper",
    "Anti-Aircraft Trailer",
    "Rogue",
    "Raiju",
    "F-160 Raiju"
}